# Configuración global del proyecto
project_id = "fuelflow_core"

[api]
enabled = true
max_rows = 1000 # Límite de seguridad para evitar consultas masivas accidentales
# Comentados por incompatibilidad con el schema local del CLI:
# db_pool_min = 1
# db_pool_max = 20

[db]
port = 5432
shadow_port = 5433

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20

# Asegurar que pg_net tiene permiso para operar en el background
[db.settings]
# shared_preload_libraries = "pg_stat_statements,pg_net"

[realtime]
enabled = true

[analytics]
enabled = true

[functions.webhook-geometry-ingest]
enabled = true
verify_jwt = false
import_map = "./functions/webhook-geometry-ingest/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-geometry-ingest/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-geometry-ingest/*.html" ]
