import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '../lib/supabase';
import type { AssetInsert } from '@fuelflow/shared-types';
import { useCurrentProfile } from './useCurrentProfile';
import type { AssetFormData } from '../schemas/assetSchema';

export const useCreateAsset = () => {
  const queryClient = useQueryClient();
  const { data: profile } = useCurrentProfile();

  return useMutation({
    mutationFn: async (formData: AssetFormData) => {
      // 1. Obtener la sesión actual para extraer auth.uid()
      const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
      
      if (sessionError || !sessionData.session) {
        throw new Error('No hay sesión activa o hubo un error al obtenerla.');
      }

      const fleetId = profile?.fleet_id;

      if (!fleetId) {
        throw new Error('No se ha detectado el Fleet ID de tu perfil. Recarga la página.');
      }

      // 2. Ensamblar la carga útil B2B final (identidad inyectada)
      const payload: AssetInsert = {
        ...formData,
        fleet_id: fleetId, // Inyectado desde el hook useCurrentProfile
        // PostgreSQL maneja id y created_at automáticamente, pero si TypeScript lo requiere, lo forzamos.
      } as unknown as AssetInsert; // Type assertion since id and created_at are generated by DB. Wait, actually AssetInsert has id and created_at as optional because it's the Insert type. So this is perfect.

      // 3. Ejecutar la inserción en Supabase
      const { data, error } = await supabase
        .from('assets')
        .insert(payload as any)
        .select()
        .single();

      if (error) {
        console.error('Error insertando activo:', error);
        throw new Error(error.message);
      }

      return data;
    },
    onSuccess: () => {
      // Invalidar caché de react query para redibujar el dashboard instantáneamente
      queryClient.invalidateQueries({ queryKey: ['assets'] });
    },
  });
};
